AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  s3-to-sns

  Sample SAM Template for s3-to-sns


Parameters:
  S3BucketName: 
    Type: String
    Description: Name of the the S3 source bucket.

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket 
    Properties: 
      BucketName: !Ref S3BucketName
  S3ToSNS:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 30
      CodeUri: s3tosns/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket:
              Ref: SourceBucket     # This must be the name of an S3 bucket declared in the same template file
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: suffix      # or "suffix"
                  Value: mp4      # The value to search for in the S3 object key names


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
