AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  s3-to-sns

  Sample SAM Template for s3-to-sns


Parameters:
  S3BucketName: 
    Type: String
    Description: Name of the the S3 source bucket.
  SNSTopicName:
    Type: String
    Description: SNS Delivery topic name.
  SMSPhoneNumber:
    Type: String
    Description: Phonenumber for SMS Delivery.
  SMSPhoneNumber2:
    Type: String
    Description: Phonenumber for SMS Delivery.

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket 
    Properties: 
      BucketName: !Ref S3BucketName
      AccessControl: "PublicRead"
  SNSDeliveryTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - 
          Endpoint: !Ref SMSPhoneNumber
          Protocol: "sms"
        - 
          Endpoint: !Ref SMSPhoneNumber2
          Protocol: "sms"
      TopicName: !Ref SNSTopicName
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: !Sub '${S3BucketName}-Policy'
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref SourceBucket
                - /*
      Bucket: !Ref SourceBucket
  S3ToSNS:
    Type: AWS::Serverless::Function 
    Properties:
      Timeout: 30
      CodeUri: s3tosns/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - 
          SNSPublishMessagePolicy:
            TopicName: !GetAtt SNSDeliveryTopic.TopicName
      Environment:
        Variables:
          SNS_DESTINATION: 
            Ref: SNSDeliveryTopic
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket:
              Ref: SourceBucket     # This must be the name of an S3 bucket declared in the same template file
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: suffix      # or "suffix"
                  Value: .mp4      # The value to search for in the S3 object key names


